/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RoboyCognition
{
    public class AudioInfo : Message
    {
        public const string RosMessageName = "roboy_cognition_msgs/AudioInfo";

        public float[] frequency { get; set; }
        public float[] average_power { get; set; }

        public AudioInfo()
        {
            this.frequency = new float[0];
            this.average_power = new float[0];
        }

        public AudioInfo(float[] frequency, float[] average_power)
        {
            this.frequency = frequency;
            this.average_power = average_power;
        }
    }
}
