/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RoboyCognition
{
    public class AudioLocation : Message
    {
        public const string RosMessageName = "roboy_cognition_msgs/AudioLocation";

        public int id { get; set; }
        public string type { get; set; }
        public float[] x { get; set; }
        public float[] y { get; set; }
        public float[] z { get; set; }
        public float[] energy { get; set; }

        public AudioLocation()
        {
            this.id = 0;
            this.type = "";
            this.x = new float[0];
            this.y = new float[0];
            this.z = new float[0];
            this.energy = new float[0];
        }

        public AudioLocation(int id, string type, float[] x, float[] y, float[] z, float[] energy)
        {
            this.id = id;
            this.type = type;
            this.x = x;
            this.y = y;
            this.z = z;
            this.energy = energy;
        }
    }
}
