/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RoboyCognition
{
    public class FaceCoordinates : Message
    {
        public const string RosMessageName = "roboy_cognition_msgs/FaceCoordinates";

        // stored id to facial features
        public int id { get; set; }
        // is person speaking?
        public bool speaking { get; set; }
        // 3D position of person in transformed global coordinates
        public float x { get; set; }
        public float y { get; set; }
        public float z { get; set; }

        public FaceCoordinates()
        {
            this.id = 0;
            this.speaking = false;
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
        }

        public FaceCoordinates(int id, bool speaking, float x, float y, float z)
        {
            this.id = id;
            this.speaking = speaking;
            this.x = x;
            this.y = y;
            this.z = z;
        }
    }
}
