/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RoboyCognition
{
    public class RecognizedSpeech : Message
    {
        public const string RosMessageName = "roboy_cognition_msgs/RecognizedSpeech";

        public short source { get; set; }
        public string text { get; set; }
        public double start_timestamp { get; set; }

        public RecognizedSpeech()
        {
            this.source = 0;
            this.text = "";
            this.start_timestamp = 0.0;
        }

        public RecognizedSpeech(short source, string text, double start_timestamp)
        {
            this.source = source;
            this.text = text;
            this.start_timestamp = start_timestamp;
        }
    }
}
