/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RoboyCognition
{
    public class RecognizedFaces : Message
    {
        public const string RosMessageName = "roboy_cognition_msgs/RecognizedFaces";

        public string[] names { get; set; }
        public double[] confidence { get; set; }

        public RecognizedFaces()
        {
            this.names = new string[0];
            this.confidence = new double[0];
        }

        public RecognizedFaces(string[] names, double[] confidence)
        {
            this.names = names;
            this.confidence = confidence;
        }
    }
}
