/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.RoboyCognition
{
    public class SpeechSynthesis : Message
    {
        public const string RosMessageName = "roboy_cognition_msgs/SpeechSynthesis";

        public Header header { get; set; }
        public string phoneme { get; set; }
        public int duration { get; set; }

        public SpeechSynthesis()
        {
            this.header = new Header();
            this.phoneme = "";
            this.duration = 0;
        }

        public SpeechSynthesis(Header header, string phoneme, int duration)
        {
            this.header = header;
            this.phoneme = phoneme;
            this.duration = duration;
        }
    }
}
