/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.RoboyControl
{
    public class Emotion : Message
    {
        public const string RosMessageName = "roboy_control_msgs/Emotion";

        public Header header { get; set; }
        public string emotion { get; set; }

        public Emotion()
        {
            this.header = new Header();
            this.emotion = "";
        }

        public Emotion(Header header, string emotion)
        {
            this.header = header;
            this.emotion = emotion;
        }
    }
}
