/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RoboyControl
{
    public class FingerCommand : Message
    {
        public const string RosMessageName = "roboy_control_msgs/FingerCommand";

        public byte id { get; set; }
        public byte finger { get; set; }
        public byte[] angles { get; set; }

        public FingerCommand()
        {
            this.id = 0;
            this.finger = 0;
            this.angles = new byte[0];
        }

        public FingerCommand(byte id, byte finger, byte[] angles)
        {
            this.id = id;
            this.finger = finger;
            this.angles = angles;
        }
    }
}
