/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RoboyControl
{
    public class StartRecordTrajectory : Message
    {
        public const string RosMessageName = "roboy_control_msgs/StartRecordTrajectory";

        public string name { get; set; }
        public string[] body_parts { get; set; }
        //  to record
        public sbyte[] id_list { get; set; }

        public StartRecordTrajectory()
        {
            this.name = "";
            this.body_parts = new string[0];
            this.id_list = new sbyte[0];
        }

        public StartRecordTrajectory(string name, string[] body_parts, sbyte[] id_list)
        {
            this.name = name;
            this.body_parts = body_parts;
            this.id_list = id_list;
        }
    }
}
