/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RoboyCognition
{
    public class DirectionVector : Message
    {
        public const string RosMessageName = "roboy_cognition_msgs/DirectionVector";

        public double azimutal_angle { get; set; }
        public double polar_angle { get; set; }

        public DirectionVector()
        {
            this.azimutal_angle = 0.0;
            this.polar_angle = 0.0;
        }

        public DirectionVector(double azimutal_angle, double polar_angle)
        {
            this.azimutal_angle = azimutal_angle;
            this.polar_angle = polar_angle;
        }
    }
}
