/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;
using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.RoboyCognition
{
    public class IceCream : Message
    {
        public const string RosMessageName = "roboy_cognition_msgs/IceCream";

        public string flavor { get; set; }
        public Pose pose { get; set; }
        public Float32MultiArray point_cloud { get; set; }

        public IceCream()
        {
            this.flavor = "";
            this.pose = new Pose();
            this.point_cloud = new Float32MultiArray();
        }

        public IceCream(string flavor, Pose pose, Float32MultiArray point_cloud)
        {
            this.flavor = flavor;
            this.pose = pose;
            this.point_cloud = point_cloud;
        }
    }
}
