/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RoboyControl
{
    public class Behavior : Message
    {
        public const string RosMessageName = "roboy_control_msgs/Behavior";

        public string name { get; set; }
        public string[] actions { get; set; }

        public Behavior()
        {
            this.name = "";
            this.actions = new string[0];
        }

        public Behavior(string name, string[] actions)
        {
            this.name = name;
            this.actions = actions;
        }
    }
}
