/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.RoboyControl
{
    public class Strings : Message
    {
        public const string RosMessageName = "roboy_control_msgs/Strings";

        public string[] names { get; set; }

        public Strings()
        {
            this.names = new string[0];
        }

        public Strings(string[] names)
        {
            this.names = names;
        }
    }
}
